project:
  type: website
  output-dir: docs

website:
  title: My Personnal Projects
  reader-mode: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Science"
        file: science.qmd
      - text: "About"
        file: about.qmd
      - text: "Music"
        file: music.qmd

  sidebar:
    - title: "My works in science"
      style: "docked"
      background: light
      contents:
      - science.qmd
      - auto: internships

    - title: "Home"
      contents:
        - index.qmd

    - title: "Music"
      contents:
      - music.qmd

format:
  html:
    theme: 
      light: mystyle.scss
      dark: [mystyle.scss, theme-dark.scss]
    mainfont: Roboto
      # light: cosmo
      # dark: slate
    css: styles.css
    toc: true



