project:
  type: website
  output-dir: docs

website:
  title: "My Personnal Projects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - science.qmd

format:
  html:
    theme: 
      - mystyle.scss
    mainfont: Zilla Slab
      # light: cosmo
      # dark: slate
    css: styles.css
    toc: true



